//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerProduct
    {
        public int FarmerProductID { get; set; }
        public string FarmerUsername { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        public virtual Product Product { get; set; }
    }
}
